name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Display Docker version for debugging
      - name: Check Docker version
        run: docker --version
      
      # Simplify - just use standard Docker command
      - name: Build Docker image
        run: |
          # Ensure we're using the standard Docker build (not buildx)
          docker version
          docker build -t "$DOCKER_USERNAME/ai-toc-builder:latest" .
          docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "Logged in to Docker Hub as ${{ secrets.DOCKER_USERNAME }}"
      
      # Push the image with detailed debugging
      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          echo "Checking Docker Hub repositories..."
          # Ensure lowercase repository name for Docker Hub
          REPO_NAME="ai-toc-builder"
          REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          DOCKER_USERNAME_LOWER=$(echo ${DOCKER_USERNAME} | tr '[:upper:]' '[:lower:]')
          
          echo "Attempting to push to: ${DOCKER_USERNAME_LOWER}/${REPO_NAME_LOWER}:latest"
          # Tag with lowercase to ensure Docker Hub compatibility
          docker tag ${DOCKER_USERNAME}/ai-toc-builder:latest ${DOCKER_USERNAME_LOWER}/${REPO_NAME_LOWER}:latest
          
          # Push with detailed output
          docker push --debug ${DOCKER_USERNAME_LOWER}/${REPO_NAME_LOWER}:latest || {
            echo "Push failed. This could be because:"
            echo "1. The repository doesn't exist yet and needs to be created manually"
            echo "2. The Docker token doesn't have push access to this repository"
            echo "3. There's a namespace issue with the Docker username"
            
            echo "Trying fallback approach..."
            # Try different tagging approach as fallback
            docker tag ${DOCKER_USERNAME}/ai-toc-builder:latest docker.io/${DOCKER_USERNAME_LOWER}/${REPO_NAME_LOWER}:latest
            docker push docker.io/${DOCKER_USERNAME_LOWER}/${REPO_NAME_LOWER}:latest
          }
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
